name: Test and merge

on:
  pull_request_target:
    branches:
      - main

env:
  BUILD_TYPE: Release

jobs:
  test:
    name: ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    if: ${{ github.actor == 'dependabot[bot]' }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        platform: [ "windows-latest", "ubuntu-latest", "macos-latest" ]
    permissions:
      actions: write

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: "refs/pull/${{ github.event.number }}/merge"

      - name: Install Cmake 3.23
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install cmake-data
          wget -O cmake.sh https://cmake.org/files/v3.23/cmake-3.23.2-linux-x86_64.sh
          sudo bash cmake.sh --skip-license --exclude-subdir --prefix=/usr/local
        shell: bash

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}} -L anyplatform --output-on-failure

  auto-merge:
    name: "Auto-merge Dependabot PRs"
    needs: test
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: "Get Dependabot metadata"
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1.1.1
        with:
          github-token: ${{ github.token }}

      - name: "Approve the PR"
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.PAT }}

      # Don't auto-merge major version updates
      - name: "Auto-merge the PR"
        if: ${{ steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major' }}
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.PAT }}