name: Build C-Blosc

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        build_type: [ Debug, Release ]
        platform: [ "macos-latest" ]

    runs-on: ${{ matrix.platform }}

    permissions:
      actions: write

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3
        with:
          repository: Blosc/c-blosc
          ref: v1.21.4

      - name: CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DBUILD_SHARED=OFF -DBUILD_TESTS=OFF -DBUILD_FUZZERS=OFF -DBUILD_BENCHMARKS=OFF -DCMAKE_OSX_ARCHITECTURE="arm64;x86_64"

      - name: Build
        run: |
          cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}
          cpack --config ${{github.workspace}}/build/CPackConfig.cmake -C ${{matrix.build_type}} -G ZIP

      - uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.platform}} ${{matrix.build_type}} binaries
          path: ${{github.workspace}}/*.zip