name: Build AWS SDK C++ for Windows, Linux, and MacOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build aws-sdk-cpp ${{ matrix.build_type }} on ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        platform:
          - windows-latest
          - ubuntu-latest
          - macos-latest
        build_type:
          - Debug
          - Release
          - RelWithDebInfo
    permissions:
      actions: write

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - name: Install Dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install libcurl-dev

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: aws/aws-sdk-cpp
          ref: 1.11.315

      - name: Checkout submodules
        run: git submodule update --init --recursive
        working-directory: aws-sdk-cpp

      - name: Configure
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install -DBUILD_ONLY="s3" -DENABLE_TESTING=OFF aws-sdk-cpp

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

      - name: Install
        run: cmake --install ${{github.workspace}}/build --config ${{matrix.build_type}}

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: aws-sdk-cpp-${{matrix.build_type}}-${{matrix.platform}}
          path: ${{github.workspace}}/install