name: Create nightly release

on:
  schedule:
    - cron: "0 5 * * *"  # runs at 5 AM UTC
  pull_request: # TODO (aliddell): delete me
    branches: [ "main" ]

jobs:
  nightly-build:
    strategy:
      matrix:
        build_type: [ Debug, Release ]
        platform: [ "windows-latest", "ubuntu-latest", "macos-latest" ]

    runs-on: ${{ matrix.platform }}

    permissions:
      actions: write

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

      - name: Build
        run: |
          cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}
          cpack --config ${{github.workspace}}/build/CPackConfig.cmake -C ${{matrix.build_type}} -G ZIP

      - uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.platform}} ${{matrix.build_type}} binaries
          path: ${{github.workspace}}/*.zip

  nightly-release:
    needs: nightly-build
    name: "Nightly Release"
    runs-on: "ubuntu-latest"

    permissions: write-all

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ github.token }}"
          automatic_release_tag: "nightly"
          prerelease: true
          title: "Development Build"
          files: |
            *.zip